[build]
  base = "/"
  command = "pip install -r requirements.txt"
  publish = ""

[build.environment]
  PYTHON_VERSION = "3.10"
  PYTHONUNBUFFERED = "1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/hello"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"